version: "2.3"
services:
    ubuntu16:
        build: ./docker
        container_name: ubuntu16
        tty: true
        volumes:
            - ./zsh:/dotfiles/zsh
            - ./nvim:/dotfiles/nvim
